// GENERADO desde el export de WordPress. No editar a mano.
// Regenerar con el pipeline descrito en REVISION-ARTICULOS.md.
//
// Solo metadatos: este módulo lo importan la Home y el índice, y debe poder
// entrar también en componentes de cliente. El contenido de cada nota vive en
// src/content/articulos/<slug>.json y se lee con fs desde notas-content.ts, para
// que los ~460 KB de HTML no acaben en el bundle de una tarjeta de listado.

export type ArticuloImagen = { src: string; w: number; h: number };

export type ArticuloMeta = {
  slug: string;
  titulo: string;
  fecha: string;
  excerpt: string;
  categorias: string[];
  /** null en las notas que el export de WordPress no traía con imagen destacada. */
  imagen: ArticuloImagen | null;
};

/** Todas las notas publicadas, de más reciente a más antigua. */
export const ARTICULOS: ArticuloMeta[] = [
  {"slug": "guia-sobre-la-doble-materialidad", "titulo": "Doble materialidad: Qué es y cómo soluciona tu estrategia ESG", "fecha": "2025-12-02", "excerpt": "Explora cómo la doble materialidad se ha convertido en una herramienta estratégica clave para las empresas que desean ir más allá del simple reporte y convertir estos análisis en acciones que agreguen valor y fortalezcan la relación con los grupos de interés.", "categorias": ["Doble Materialidad"], "imagen": {"src": "/articulos/guia-sobre-la-doble-materialidad.jpg", "w": 2560, "h": 1707}},
  {"slug": "guia-sobre-sostenibilidad-empresarial", "titulo": "Sostenibilidad empresarial: Qué es y cómo implementarla con éxito", "fecha": "2025-10-07", "excerpt": "Qué es la sostenibilidad empresarial y cómo implementarla: gestión de riesgos, uso eficiente de recursos y rentabilidad a largo plazo para su organización.", "categorias": ["Blog"], "imagen": {"src": "/articulos/guia-sobre-sostenibilidad-empresarial.jpg", "w": 2560, "h": 1707}},
  {"slug": "guia-sobre-los-stakeholders", "titulo": "Tipos de stakeholders en una empresa y cómo gestionarlos correctamente ", "fecha": "2025-09-01", "excerpt": "Descubre cómo clasificar, priorizar y relacionarte con tus grupos de interés para impulsar una RSE sólida y estratégica.", "categorias": ["Blog"], "imagen": {"src": "/articulos/guia-sobre-los-stakeholders.jpg", "w": 2560, "h": 1707}},
  {"slug": "guia-calcular-retorno-social", "titulo": "Webinar “Del donativo al impacto: Cómo calcular el retorno social de tus proyectos con participación especial de BMW Group Planta SLP” ", "fecha": "2025-08-26", "excerpt": "Webinar sobre SROI con BMW Group Planta San Luis Potosí: cómo medir el retorno social de sus proyectos y pasar del donativo al impacto demostrable.", "categorias": ["Blog"], "imagen": {"src": "/articulos/guia-calcular-retorno-social.jpg", "w": 1024, "h": 682}},
  {"slug": "guia-analisis-de-materialidad", "titulo": "Análisis de materialidad: cómo definir prioridades ASG en tu empresa ", "fecha": "2025-08-18", "excerpt": "Cómo definir prioridades ASG a partir de sus grupos de interés: qué son los stakeholders, cómo identificarlos y cómo traducir sus expectativas en decisiones.", "categorias": ["Distintivo ESR", "Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/guia-analisis-de-materialidad.jpg", "w": 2560, "h": 1440}},
  {"slug": "claves-integrar-doble-materialidad", "titulo": "Doble materialidad: 5 claves para su estrategia", "fecha": "2025-08-04", "excerpt": "Cinco claves para integrar la doble materialidad en su estrategia y convertir la sostenibilidad en una herramienta de gestión de riesgos y de decisión.", "categorias": ["Doble Materialidad"], "imagen": {"src": "/articulos/claves-integrar-doble-materialidad.jpg", "w": 2560, "h": 1440}},
  {"slug": "guia-responsabilidad-social-empresarial-pymes", "titulo": "9 consejos para incorporar la Responsabilidad Social Empresarial en PyMEs", "fecha": "2025-05-15", "excerpt": "Nueve consejos prácticos para incorporar la responsabilidad social empresarial en una PyME, con los retos habituales y cómo resolverlos paso a paso.", "categorias": ["Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/guia-responsabilidad-social-empresarial-pymes.jpg", "w": 2560, "h": 1708}},
  {"slug": "guia-reporte-de-sustentabilidad", "titulo": "Reporte de sustentabilidad: Guía para estructurarlo bajo estándares GRI", "fecha": "2024-09-25", "excerpt": "Cómo estructurar un reporte de sustentabilidad bajo los estándares GRI, para comunicar sus avances con transparencia y reducir riesgos reputacionales.", "categorias": ["Sostenibilidad"], "imagen": {"src": "/articulos/guia-reporte-de-sustentabilidad.jpg", "w": 2560, "h": 1928}},
  {"slug": "como-desarrollar-tu-estrategia-de-rse-con-la-metodologia-resilio", "titulo": "Cómo desarrollar tu estrategia de RSE con la metodología RESILIO", "fecha": "2024-06-06", "excerpt": "ResponSable, te ofrece una oportunidad única para conocer en una metodología que ha transformado a más de 250 empresas. A diferencia de otros enfoques, la metodología RESILIO se basa en experiencias prácticas y resultados comprobados, garantizando que cada paso te acerque más a tus objetivos de sostenibilidad.", "categorias": ["Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/como-desarrollar-tu-estrategia-de-rse-con-la-metodologia-resilio.png", "w": 1024, "h": 576}},
  {"slug": "desarrollando-nuevas-estrategias-en-responsabilidad-social-corporativa", "titulo": "Desarrollando nuevas estrategias en Responsabilidad Social Corporativa, con la participación de BMW Group Planta SLP", "fecha": "2024-05-02", "excerpt": "Expertos de BMW Group Planta SLP comparten insights valiosos sobre cómo adaptar estrategias de RSC globales a necesidades locales.", "categorias": ["Estrategia de RSE", "Proyectos ResponSable"], "imagen": {"src": "/articulos/desarrollando-nuevas-estrategias-en-responsabilidad-social-corporativa.png", "w": 1024, "h": 576}},
  {"slug": "nuevas-estrategias-para-una-postulacion-exitosa-al-distintivo-esr-2024", "titulo": "Nuevas estrategias para una postulación exitosa al distintivo ESR 2024", "fecha": "2024-03-04", "excerpt": "Estrategias para preparar una postulación exitosa al Distintivo ESR 2024 y demostrar un compromiso social auténtico que diferencie a su empresa.", "categorias": ["Distintivo ESR"], "imagen": {"src": "/articulos/nuevas-estrategias-para-una-postulacion-exitosa-al-distintivo-esr-2024.png", "w": 2048, "h": 1152}},
  {"slug": "como-realizar-un-diagnostico-de-impacto-social-efectivo", "titulo": "¿Cómo realizar un diagnóstico de impacto social efectivo?", "fecha": "2023-11-24", "excerpt": "Cómo realizar un diagnóstico de impacto social efectivo: entender las necesidades reales de la comunidad y sustituir el asistencialismo por estrategia.", "categorias": ["Beneficios de la RS", "Proyectos ResponSable"], "imagen": {"src": "/articulos/como-realizar-un-diagnostico-de-impacto-social-efectivo.png", "w": 1024, "h": 576}},
  {"slug": "como-construir-una-cadena-de-valor-y-guiar-a-las-pymes-hacia-los-ods", "titulo": "¿Cómo construir una cadena de valor responsable y guiar a las PyMEs hacia los ODS, con un programa estratégico?", "fecha": "2023-11-13", "excerpt": "El programa Campeonas por los ODS de CEMEX como modelo para construir una cadena de valor responsable y guiar a las PyMEs proveedoras hacia los ODS.", "categorias": ["Beneficios de la RS", "Blog", "Estrategia de RSE"], "imagen": {"src": "/articulos/como-construir-una-cadena-de-valor-y-guiar-a-las-pymes-hacia-los-ods.png", "w": 1024, "h": 576}},
  {"slug": "como-superar-desafios-rse-sector-industrial", "titulo": "Cómo superar los desafíos de la RSE en el Sector Industrial", "fecha": "2023-10-13", "excerpt": "Los desafíos propios de la RSE en el sector industrial y cómo superarlos, en un entorno donde las prácticas sostenibles dejaron de ser opcionales.", "categorias": ["Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/como-superar-desafios-rse-sector-industrial.jpg", "w": 2143, "h": 1232}},
  {"slug": "nuevo-modelo-distintivo-esr-2023-pymes", "titulo": "El nuevo modelo del Distintivo ESR® 2023: Guía para PyMEs", "fecha": "2023-09-18", "excerpt": "Guía del nuevo modelo del Distintivo ESR 2023 para PyMEs: qué cambia en la evaluación, qué se exige y cómo puede prepararse una empresa pequeña.", "categorias": ["Distintivo ESR", "Responsabilidad Social Empresarial"], "imagen": null},
  {"slug": "el-abc-de-la-responsabilidad-social-empresarial", "titulo": "El ABC de la Responsabilidad Social Empresarial", "fecha": "2023-07-20", "excerpt": "Introducción a la responsabilidad social empresarial para quien se acerca por primera vez: qué es, desde qué ángulos se aborda y por dónde empezar.", "categorias": ["Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/el-abc-de-la-responsabilidad-social-empresarial.png", "w": 496, "h": 523}},
  {"slug": "conoce-los-7-pasos-para-triunfar-en-tu-estrategia-de-rse", "titulo": "Conoce los 7 pasos para triunfar en tu estrategia de RSE", "fecha": "2023-04-03", "excerpt": "Los siete pasos de RESILIO, la metodología que ResponSable construyó en quince años, para diseñar, implementar y comunicar una estrategia de RSE.", "categorias": ["Blog"], "imagen": {"src": "/articulos/conoce-los-7-pasos-para-triunfar-en-tu-estrategia-de-rse.jpg", "w": 1081, "h": 643}},
  {"slug": "quieres-obtener-el-distintivo-esr-en-2023-conoce-los-cambios-en-la-convocatoria-y-preparate", "titulo": "¿Quieres obtener el Distintivo ESR en 2023? Conoce los cambios en la convocatoria y prepárate", "fecha": "2023-03-22", "excerpt": "Los cambios de la convocatoria del Distintivo ESR 2023 y cómo prepararse: qué evalúa el reconocimiento del Cemefi y qué debe reunir su empresa.", "categorias": ["Distintivo ESR"], "imagen": {"src": "/articulos/quieres-obtener-el-distintivo-esr-en-2023-conoce-los-cambios-en-la-convocatoria-y-preparate.png", "w": 600, "h": 400}},
  {"slug": "tips-para-reportar-con-los-nuevos-estandares-gri", "titulo": "Tips para reportar con los nuevos estándares GRI", "fecha": "2022-10-14", "excerpt": "Webinar sobre los estándares GRI vigentes desde enero de 2023: qué cambia frente a GRI Standards 2016 y cómo adaptar su reporte de sostenibilidad.", "categorias": ["Blog"], "imagen": null},
  {"slug": "5-consejos-de-responsabilidad-social-empresarial-rse-que-no-cuestan-casi-nada", "titulo": "5 consejos de Responsabilidad Social Empresarial (RSE) que no cuestan casi nada", "fecha": "2022-09-27", "excerpt": "Cinco acciones de responsabilidad social de costo mínimo, centradas en condiciones laborales y gestión cotidiana, para empezar sin presupuesto.", "categorias": ["Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/5-consejos-de-responsabilidad-social-empresarial-rse-que-no-cuestan-casi-nada.jpg", "w": 1280, "h": 850}},
  {"slug": "lo-que-no-te-dicen-al-iniciar-una-estrategia-de-sostenibilidad", "titulo": "Lo que no te dicen al iniciar una Estrategia de Sostenibilidad", "fecha": "2022-08-04", "excerpt": "Lo que rara vez se advierte al iniciar una estrategia de sostenibilidad, con la experiencia de Profuturo y Grupo BAL tras su diagnóstico ISO 26000.", "categorias": ["Sostenibilidad"], "imagen": {"src": "/articulos/lo-que-no-te-dicen-al-iniciar-una-estrategia-de-sostenibilidad.jpg", "w": 4286, "h": 2465}},
  {"slug": "analisis-de-materialidad-mas-alla-de-un-requisito-para-reportar", "titulo": "Análisis de materialidad: Más allá de un requisito para reportar", "fecha": "2022-07-29", "excerpt": "El análisis de materialidad como ejercicio estratégico y no solo como requisito GRI: cómo priorizar los temas que sus grupos de interés consideran críticos.", "categorias": ["Blog"], "imagen": {"src": "/articulos/analisis-de-materialidad-mas-alla-de-un-requisito-para-reportar.jpg", "w": 5642, "h": 3175}},
  {"slug": "los-desafios-de-desarrollar-una-estrategia-de-sustentabilidad-exitosa", "titulo": "Los desafíos de desarrollar una estrategia de Sustentabilidad Exitosa", "fecha": "2022-06-02", "excerpt": "Los desafíos de construir una estrategia de sustentabilidad que resista la exigencia de inversionistas, clientes y consumidores por rendir cuentas.", "categorias": ["Sustentabilidad"], "imagen": {"src": "/articulos/los-desafios-de-desarrollar-una-estrategia-de-sustentabilidad-exitosa.png", "w": 1182, "h": 1182}},
  {"slug": "cuales-son-los-beneficios-de-aplicar-practicas-de-rs-en-las-pymes", "titulo": "¿Cuáles son los beneficios de aplicar prácticas de RSE en las PyMEs?", "fecha": "2022-02-23", "excerpt": "Los beneficios concretos de aplicar prácticas de RSE en una PyME, donde la cercanía con el entorno y con el cliente convierte la gestión en ventaja.", "categorias": ["Responsabilidad Social Empresarial"], "imagen": {"src": "/articulos/cuales-son-los-beneficios-de-aplicar-practicas-de-rs-en-las-pymes.png", "w": 592, "h": 592}},
  {"slug": "heineken-mexico-pasos-estrategicos-para-un-estudio-de-materialidad-fuera-de-lo-comun", "titulo": "HEINEKEN México – Pasos Estratégicos para un Estudio de Materialidad Fuera de lo Común", "fecha": "2022-01-11", "excerpt": "Conversación con HEINEKEN México sobre su estudio de materialidad: cómo se definen los temas materiales, a quién consultar y cuánto tiempo exige.", "categorias": ["Beneficios de la RS", "Blog", "Estrategia de RSE", "Proyectos ResponSable"], "imagen": {"src": "/articulos/heineken-mexico-pasos-estrategicos-para-un-estudio-de-materialidad-fuera-de-lo-comun.png", "w": 501, "h": 439}},
  {"slug": "responshable-2-resolvemos-las-dudas-de-responsabilidad-social-en-tu-empresa", "titulo": "ResponsHABLE 2 – Resolvemos las dudas de Responsabilidad Social en tu Empresa", "fecha": "2021-11-29", "excerpt": "Segunda sesión de ResponsHABLE: respuestas sobre identificación de ODS, relacionamiento con grupos de interés y RSE después de la pandemia.", "categorias": ["Blog"], "imagen": {"src": "/articulos/responshable-2-resolvemos-las-dudas-de-responsabilidad-social-en-tu-empresa.jpg", "w": 5001, "h": 5001}},
  {"slug": "responshable-1-resolvemos-las-dudas-de-responsabilidad-social-en-tu-empresa", "titulo": "ResponsHABLE 1 – Resolvemos las dudas de Responsabilidad Social en tu Empresa", "fecha": "2021-10-29", "excerpt": "Primera sesión de ResponsHABLE: por qué la responsabilidad social va más allá del cumplimiento legal y qué beneficios genera un enfoque estratégico.", "categorias": ["Blog"], "imagen": {"src": "/articulos/responshable-1-resolvemos-las-dudas-de-responsabilidad-social-en-tu-empresa.jpg", "w": 5000, "h": 5001}},
  {"slug": "los-desastres-no-son-naturales", "titulo": "¡Los desastres no son naturales!", "fecha": "2021-10-13", "excerpt": "Relato en primera persona del sismo de 2017 y la pérdida de las oficinas: lo que la crisis enseñó sobre resiliencia organizacional y gestión de riesgos.", "categorias": ["Blog"], "imagen": {"src": "/articulos/los-desastres-no-son-naturales.jpg", "w": 960, "h": 599}},
  {"slug": "el-a-b-c-de-la-actualizacion-de-los-estandares-de-gri", "titulo": "El A, B, C de la actualización de los Estándares de GRI", "fecha": "2021-10-08", "excerpt": "La actualización más ambiciosa de los Estándares GRI desde 2016: por qué se hizo, cuáles son los cambios principales y a partir de cuándo aplican.", "categorias": ["Blog"], "imagen": {"src": "/articulos/el-a-b-c-de-la-actualizacion-de-los-estandares-de-gri.png", "w": 250, "h": 200}},
  {"slug": "informes-de-sustentabilidad-por-donde-empezar", "titulo": "Informes de Sustentabilidad: ¿por dónde empezar?", "fecha": "2021-08-25", "excerpt": "Buenas prácticas para empezar un informe de sustentabilidad: cómo organizar la recopilación de información y evitar que el proceso se vuelva inmanejable.", "categorias": ["Blog"], "imagen": {"src": "/articulos/informes-de-sustentabilidad-por-donde-empezar.png", "w": 250, "h": 200}},
  {"slug": "10-errores-que-debes-evitar-en-tu-informe-de-sostenibilidad", "titulo": "10 errores que debes evitar en tu Informe de Sostenibilidad", "fecha": "2021-02-18", "excerpt": "Diez errores frecuentes al elaborar un informe de sostenibilidad, identificados en la experiencia de ResponSable acompañando a áreas de RSE.", "categorias": ["Blog"], "imagen": {"src": "/articulos/10-errores-que-debes-evitar-en-tu-informe-de-sostenibilidad.png", "w": 250, "h": 200}},
  {"slug": "responsabilidad-social-la-base-de-una-organizacion-resiliente", "titulo": "Responsabilidad Social: la base de una organización resiliente", "fecha": "2021-02-09", "excerpt": "Por qué la responsabilidad social sostiene la resiliencia organizacional: el concepto llevado del plano individual al de la empresa y su operación.", "categorias": ["Blog"], "imagen": {"src": "/articulos/responsabilidad-social-la-base-de-una-organizacion-resiliente.jpg", "w": 6048, "h": 3024}},
  {"slug": "acciones-empresariales-ante-covid-19", "titulo": "Acciones de RSE ante COVID-19", "fecha": "2020-12-14", "excerpt": "Balance de las acciones de RSE desplegadas por los distintos sectores durante el primer año de la pandemia y de sus efectos económicos y laborales.", "categorias": ["Blog"], "imagen": {"src": "/articulos/acciones-empresariales-ante-covid-19.png", "w": 1007, "h": 743}},
  {"slug": "estudio-de-materialidad-10-beneficios-estrategicos", "titulo": "Estudio de materialidad: 10 Beneficios Estratégicos", "fecha": "2020-12-07", "excerpt": "Diez beneficios estratégicos del estudio de materialidad y por qué su valor para el negocio excede el uso habitual como simple insumo para reportar.", "categorias": ["Blog"], "imagen": {"src": "/articulos/estudio-de-materialidad-10-beneficios-estrategicos.png", "w": 1301, "h": 1301}},
  {"slug": "5-razones-para-evaluar-la-madurez-de-la-rs-en-tu-empresa-usando-la-iso-26000", "titulo": "5 razones para evaluar la madurez de la RS en tu empresa usando la ISO 26000", "fecha": "2020-11-19", "excerpt": "Cinco razones para evaluar la madurez de su gestión con la ISO 26000, la norma internacional de responsabilidad social construida por 99 países.", "categorias": ["ISO 26000"], "imagen": {"src": "/articulos/5-razones-para-evaluar-la-madurez-de-la-rs-en-tu-empresa-usando-la-iso-26000.png", "w": 1200, "h": 1200}},
  {"slug": "todo-lo-que-debes-saber-sobre-compras-sostenibles-en-5-minutos", "titulo": "Todo lo que debes saber sobre Compras Sostenibles en 5 minutos", "fecha": "2020-09-28", "excerpt": "Introducción a las compras sostenibles a partir del caso Nike: por qué la cadena de suministro concentra buena parte del riesgo social de una empresa.", "categorias": ["Blog"], "imagen": {"src": "/articulos/todo-lo-que-debes-saber-sobre-compras-sostenibles-en-5-minutos.jpg", "w": 5515, "h": 3983}},
  {"slug": "asesoria-gratuita-covid19", "titulo": "¡Brindamos asesoría gratuita para enfrentar la nueva realidad en las organizaciones!", "fecha": "2020-08-04", "excerpt": "ResponSable abrió asesoría gratuita durante la pandemia, a partir de una encuesta de detección de necesidades entre clientes, aliados y empresas.", "categorias": ["Blog"], "imagen": {"src": "/articulos/asesoria-gratuita-covid19.jpg", "w": 684, "h": 456}},
  {"slug": "impartimos-talleres-de-rs-y-gestion-de-riesgos-durante-la-emergencia-de-covid-19", "titulo": "Impartimos talleres de RS y Gestión de riesgos durante la emergencia de COVID-19", "fecha": "2020-06-17", "excerpt": "Talleres de responsabilidad social y gestión de riesgos impartidos durante la emergencia sanitaria, con el video completo de la sesión con CAINTRA.", "categorias": ["Blog"], "imagen": {"src": "/articulos/impartimos-talleres-de-rs-y-gestion-de-riesgos-durante-la-emergencia-de-covid-19.png", "w": 1217, "h": 636}},
  {"slug": "a-nuestros-grupos-de-interes", "titulo": "Call to action ResponSable ante el COVID-19", "fecha": "2020-03-20", "excerpt": "Comunicado de ResponSable a sus grupos de interés ante el COVID-19: la resiliencia como respuesta a una crisis sanitaria con efectos económicos.", "categorias": ["Blog"], "imagen": {"src": "/articulos/a-nuestros-grupos-de-interes.png", "w": 1443, "h": 600}},
  {"slug": "como-empezar-un-plan-de-responsabilidad-social", "titulo": "¿Cómo empezar un plan de Responsabilidad Social?", "fecha": "2020-02-17", "excerpt": "Cómo empezar un plan de responsabilidad social cuando las normas, indicadores y metodologías disponibles dificultan saber por dónde comenzar.", "categorias": ["Blog"], "imagen": {"src": "/articulos/como-empezar-un-plan-de-responsabilidad-social.jpg", "w": 1087, "h": 691}},
  {"slug": "distintivo-esr-importancia-cadena-de-valor", "titulo": "La importancia del Distintivo ESR en la cadena de valor", "fecha": "2020-02-14", "excerpt": "Por qué el Distintivo ESR importa en la cadena de valor: extender las buenas prácticas a todo el proceso comercial reduce el riesgo legal y reputacional.", "categorias": ["Blog"], "imagen": {"src": "/articulos/distintivo-esr-importancia-cadena-de-valor.jpg", "w": 6000, "h": 4105}},
  {"slug": "impartimos-cursos-y-talleres-de-responsabilidad-social-este-2019", "titulo": "¡Impartimos cursos y talleres de responsabilidad social este 2019!", "fecha": "2019-12-30", "excerpt": "Balance de los cursos y talleres de responsabilidad social impartidos en 2019 con empresas y organismos promotores de la RSE en México.", "categorias": ["Blog"], "imagen": {"src": "/articulos/impartimos-cursos-y-talleres-de-responsabilidad-social-este-2019.jpg", "w": 1280, "h": 809}},
  {"slug": "datos-que-revelan-el-estado-de-la-rs-en-mexico", "titulo": "Responsabilidad Social: Cinco datos que revelan su estado en México", "fecha": "2019-11-19", "excerpt": "Cinco datos sobre el estado de la responsabilidad social en México: percepción de rentabilidad, presupuesto asignado y situación en las MiPyMEs.", "categorias": ["Blog"], "imagen": {"src": "/articulos/datos-que-revelan-el-estado-de-la-rs-en-mexico.jpg", "w": 668, "h": 415}},
  {"slug": "equidad-de-genero-y-responsabilidad-social", "titulo": "Equidad de género y responsabilidad social", "fecha": "2019-10-21", "excerpt": "El Ranking PAR México 2019 leído desde la responsabilidad social: qué revela sobre las brechas de género en las organizaciones latinoamericanas.", "categorias": ["Blog"], "imagen": {"src": "/articulos/equidad-de-genero-y-responsabilidad-social.jpg", "w": 2048, "h": 1366}},
  {"slug": "responsable-dos-anos-del-sismo", "titulo": "ResponSable a dos años del sismo", "fecha": "2019-09-20", "excerpt": "Dos años después del sismo que costó a ResponSable sus instalaciones y tres compañeros, el recuento de la reconstrucción con sus grupos de interés.", "categorias": ["Blog"], "imagen": {"src": "/articulos/responsable-dos-anos-del-sismo.jpg", "w": 833, "h": 833}},
  {"slug": "beneficios-de-rs-en-las-pymes", "titulo": "Beneficios de aplicar prácticas de RSE en las PyMEs", "fecha": "2019-09-09", "excerpt": "Los beneficios de aplicar prácticas de RSE en PyMEs, que suelen ejercerlas sin nombrarlas gracias a su cercanía con el entorno y con el cliente.", "categorias": ["Blog"], "imagen": {"src": "/articulos/beneficios-de-rs-en-las-pymes.jpg", "w": 726, "h": 483}},
  {"slug": "6-tips-para-postular-al-distintivo-esr-del-cemefi", "titulo": "6 Tips para postular al Distintivo ESR del Cemefi", "fecha": "2019-09-06", "excerpt": "Seis recomendaciones para postular al Distintivo ESR del Cemefi, el reconocimiento que desde el año 2000 mide el compromiso social de las empresas.", "categorias": ["Distintivo ESR"], "imagen": {"src": "/articulos/6-tips-para-postular-al-distintivo-esr-del-cemefi.png", "w": 268, "h": 200}},
  {"slug": "como-reportar-ods-en-informes-de-sustentabilidad", "titulo": "Cómo reportar ODS en tu informe de sustentabilidad en 2020", "fecha": "2019-09-02", "excerpt": "Cómo reportar los ODS en un informe de sustentabilidad, la herramienta más efectiva para comunicar la RSE a los distintos grupos de interés.", "categorias": ["Blog"], "imagen": {"src": "/articulos/como-reportar-ods-en-informes-de-sustentabilidad.jpg", "w": 6016, "h": 4016}},
  {"slug": "panorama-la-responsabilidad-social-mexico-2019", "titulo": "Panorama de la Responsabilidad Social en México 2019, ¡Hemos presentado nuestro Estudio!", "fecha": "2019-07-23", "excerpt": "Presentación de la segunda edición del estudio Panorama de la Responsabilidad Social en México 2019 en la Secretaría de Relaciones Exteriores.", "categorias": ["Blog", "Proyectos ResponSable"], "imagen": {"src": "/articulos/panorama-la-responsabilidad-social-mexico-2019.jpg", "w": 317, "h": 210}},
  {"slug": "taller-materialidad-y-dialogo-con-grupos-de-interes", "titulo": "ResponSable en Pacto Mundial México: Materialidad y diálogo con grupos de interés", "fecha": "2019-06-11", "excerpt": "Taller impartido con Pacto Mundial México sobre materialidad y diálogo con grupos de interés como pieza central de una estrategia de RSE.", "categorias": ["Blog"], "imagen": {"src": "/articulos/taller-materialidad-y-dialogo-con-grupos-de-interes.png", "w": 800, "h": 336}},
  {"slug": "panorama-de-la-responsabilidad-social-en-mexico-2019", "titulo": "Panorama de la Responsabilidad Social en México 2019, el estudio que no se construye en un día", "fecha": "2019-03-04", "excerpt": "Antesala del estudio Panorama de la Responsabilidad Social en México 2019: cómo se construyó el proyecto y qué se propuso medir. Ya está disponible.", "categorias": ["Blog"], "imagen": {"src": "/articulos/panorama-de-la-responsabilidad-social-en-mexico-2019.jpeg", "w": 1280, "h": 960}},
  {"slug": "unicef-lanza-herramienta-auto-diagnostico-empresas", "titulo": "UNICEF lanza una herramienta de auto-diagnóstico para empresas", "fecha": "2018-10-02", "excerpt": "UNICEF publica una herramienta confidencial de autodiagnóstico para que cualquier empresa mida su impacto en la niñez y en la adolescencia.", "categorias": ["Blog"], "imagen": {"src": "/articulos/unicef-lanza-herramienta-auto-diagnostico-empresas.jpg", "w": 560, "h": 292}},
  {"slug": "ranking-negocios-inclusivos-donde-desarrollo-social-encuentra-rentabilidad", "titulo": "Ranking Negocios Inclusivos: Donde el desarrollo social se encuentra con la rentabilidad", "fecha": "2018-07-19", "excerpt": "La segunda edición del Índice de Negocios Inclusivos y las empresas que integran a proveedores en situación de vulnerabilidad en su cadena.", "categorias": ["Blog"], "imagen": {"src": "/articulos/ranking-negocios-inclusivos-donde-desarrollo-social-encuentra-rentabilidad.jpg", "w": 296, "h": 388}},
  {"slug": "responsable-pacto-mundial-mexico-materialidad-dialogo-con-grupos-interes", "titulo": "ResponSable en Pacto Mundial México: Materialidad y diálogo con grupos de interés", "fecha": "2018-07-18", "excerpt": "Crónica del taller de materialidad y diálogo con grupos de interés impartido en la sede de Pacto Mundial México, con la evaluación de los asistentes.", "categorias": ["Blog"], "imagen": {"src": "/articulos/responsable-pacto-mundial-mexico-materialidad-dialogo-con-grupos-interes.jpg", "w": 1024, "h": 683}},
  {"slug": "la-responsabilidad-social-en-el-sector-alimentario-en-mexico", "titulo": "La Responsabilidad Social en el sector Alimentación y Bebidas mexicano", "fecha": "2018-07-15", "excerpt": "Datos y mejores prácticas de responsabilidad social en el sector mexicano de alimentación y bebidas, a partir del estudio Panorama de la RS.", "categorias": ["Blog"], "imagen": {"src": "/articulos/la-responsabilidad-social-en-el-sector-alimentario-en-mexico.jpg", "w": 1920, "h": 1271}},
  {"slug": "sostenibilidad-sustentabilidad-responsabilidad-social-misma-cosa", "titulo": "Sostenibilidad, Sustentabilidad, Responsabilidad Social, ¿son la misma cosa?", "fecha": "2018-05-04", "excerpt": "Sostenibilidad, sustentabilidad y responsabilidad social: qué distingue a cada término y por qué la confusión afecta la estrategia de una empresa.", "categorias": ["Blog"], "imagen": {"src": "/articulos/sostenibilidad-sustentabilidad-responsabilidad-social-misma-cosa.jpg", "w": 640, "h": 341}},
  {"slug": "19s-responsable-agencia-responsabilidad-social-continua-operaciones", "titulo": "A seis meses de ser afectados por el sismo del 19S, ResponSable, agencia de Responsabilidad Social, continúa con sus operaciones", "fecha": "2018-03-19", "excerpt": "Seis meses después del sismo del 19S, ResponSable reanuda operaciones en sus nuevas oficinas de Polanco y agradece a quienes lo hicieron posible.", "categorias": ["Noticias"], "imagen": {"src": "/articulos/19s-responsable-agencia-responsabilidad-social-continua-operaciones.jpg", "w": 874, "h": 656}},
  {"slug": "el-foro-mexico-responsable-2016-un-exito-en-la-promocion-del-how-to", "titulo": "El Foro México Responsable 2016, un éxito en la promoción del «How To…»", "fecha": "2016-03-17", "excerpt": "Crónica de los cinco años del Foro México Responsable, con más de 160 asistentes en la Secretaría de Relaciones Exteriores y acceso gratuito.", "categorias": ["Proyectos ResponSable"], "imagen": {"src": "/articulos/el-foro-mexico-responsable-2016-un-exito-en-la-promocion-del-how-to.jpg", "w": 1205, "h": 803}},
  {"slug": "las-10-recomendaciones-en-rs-de-bimbo-coca-cola-mexico-cemex-y-bio-pappel", "titulo": "Las 10 recomendaciones en RS de BIMBO, Coca-Cola México, CEMEX y Bio-Pappel", "fecha": "2015-10-09", "excerpt": "Diez recomendaciones en responsabilidad social de BIMBO, Coca-Cola México, CEMEX y Bio-Pappel, recogidas en el 2° Foro Nacional sobre RSC.", "categorias": ["Estrategia de RSE"], "imagen": {"src": "/articulos/las-10-recomendaciones-en-rs-de-bimbo-coca-cola-mexico-cemex-y-bio-pappel.jpg", "w": 684, "h": 385}},
  {"slug": "articulo-ganador-concurso-estudiantil-imagina-tu-campus-responsable", "titulo": "Artículo Ganador:  Concurso estudiantil \"Imagina tu Campus Responsable\"", "fecha": "2012-03-02", "excerpt": "Artículo ganador del concurso Imagina tu Campus Responsable: la educación como eje rector para integrar la responsabilidad social en las universidades.", "categorias": ["Proyectos ResponSable"], "imagen": {"src": "/articulos/articulo-ganador-concurso-estudiantil-imagina-tu-campus-responsable.jpg", "w": 1260, "h": 851}}
];

export function getArticuloMeta(slug: string): ArticuloMeta | undefined {
  return ARTICULOS.find((n) => n.slug === slug);
}

export function formatFecha(fecha: string): string {
  // Se construye desde las partes en vez de new Date(fecha): un ISO sin hora se
  // interpreta como UTC y en husos negativos como el de México retrocede un día.
  const [y, m, d] = fecha.split("-").map(Number);
  return new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "long", year: "numeric" })
    .format(new Date(y, m - 1, d));
}
